# Use root/example as user/password credentials
version: '3.9'

services:

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/data/db
    ports:
      - "${DB_PORT}:27017"


  backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: prod.Dockerfile
    environment:
      - DEV_PLATFORM=DOCKER
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./envs:/app/envs
    command: node dist/src/index.js
#    command: tail -f /dev/null
    deploy:
      mode: replicated
      replicas: 8

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend


volumes:
  db_data:
