# Use root/example as user/password credentials
version: '3.9'

services:

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/data/db
    ports:
      - "${DB_PORT}:27017"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s         # Time between running the check
      timeout: 5s           # Time to wait for the check to complete
      retries: 3            # How many times to retry the check
      start_period: 10s     # How long to wait before starting checks
    volumes:
      - redis-data:/data


  backend:
    depends_on:
      db:
        condition: service_started
      redis:
          condition: service_healthy
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - DEV_PLATFORM=DOCKER
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./src:/app/src
      - node-modules:/app/node_modules
      - dev-files:/app/dev-files
      - ./envs:/app/envs
    command: npm run ${NPM_COMMAND}
#    command: tail -f /dev/null
    ports:
      - "${APP_PORT}:3000"
#    deploy:
#      mode: replicated
#      replicas: 3

volumes:
  db_data:
  node-modules:
  redis-data:
  dev-files:
