# Use root/example as user/password credentials
version: '3.9'

services:

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/data/db
    ports:
      - "${DB_PORT}:27017"


  backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEV_PLATFORM=DOCKER
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./src:/app/src
      - node-modules:/app/node_modules
      - ./envs:/app/envs
    command: npm run ${NPM_COMMAND}
    ports:
      - "${APP_PORT}:3000"



volumes:
  db_data:
  node-modules:
