# Use root/example as user/password credentials
version: '3.9'

services:

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - my_network

  backend:
    image: web-sockets-chat-backend:latest
    depends_on:
      - db
    build:
      context: .
      dockerfile: prod.Dockerfile
    environment:
      - DEV_PLATFORM=DOCKER
      - NODE_ENV=staging
    volumes:
      - ./envs:/app/envs
    command: node dist/src/index.js
#    command: tail -f /dev/null
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 512m
          cpus: '0.25'
        reservations:
          cpus: '0.1'
    networks:
      - my_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
    networks:
      - my_network

volumes:
  db_data:
networks:
  my_network:
    name: prod_network
